name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'
      - '.github/workflows/*.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Rust Toolchains
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - uses: burrunan/gradle-cache-action@v1
        name: Checker
        with:
          job-id: checker
          arguments: spotlessCheck test
          gradle-version: wrapper
